dist: xenial
addons:
  snaps:
    - name: aws-cli
      confinement: classic
      channel: latest/edge

language: go
go: 1.13.x

services:
  - docker

script:
  - .ci/run_and_validate_pchain_test.sh
