dist: xenial

language: go
go: 1.13.x

services:
  - docker

before_install:
  - pip install --user awscli # need awscli to access byz-gecko images
  - export PATH=$PATH:$HOME/.local/bin # this puts user-installed pip packages on path

script:
  - .ci/run_and_validate_pchain_test.sh
